defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "Gallery"

copyright = """\
© [ZeroDream](https://github.com/zero-dream/) · \
Powered by [Hugo](https://github.com/gohugoio/hugo/) & [ZeroDream](https://github.com/zero-dream/hugo-gallery/)\
"""

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
  [[module.imports]]
    path = "github.com/zero-dream/hugo-gallery"

[params]
  defaultTheme = "dark" # light dark
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.imageSizes]
    thumbnail = "600x600"
    full = "1600x1600"
  [params.watermark]
    path = "images/watermark.png"
    opacity = 0.2
    size = 0.05
    x = 0.5
    y = 0.5
  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/"
    github = "https://github.com/zero-dream/hugo-gallery/"
    youtube = "https://www.youtube.com/"
    email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/zero-dream/hugo-gallery/"
    weight = 3

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

[services]
  [services.rss]
    limit = 100
